services:
  app:
    image: 127.0.0.1:5000/master-thesis-image-classification-app
    build: .
    ports:
      - "8000:3000"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
    command: uvicorn main:app --host 0.0.0.0 --port 3000
